### PR TITLE
update bs-platform to 7.0.1

### PR DESCRIPTION
**Pull request by leeor**
This forced a switch from let-anything to bs-let

### CODE REVIEW

**Comment by leeor** [comment]
There's an issue with mutations that have optional args, where `resolveField` seems to get an `Error` from `ArgEval.evalArgList` instead of an `Ok` which will turn into a `ResolveError` when lifted.

I'm looking into it.

**Comment by leeor** [comment]
The issue is unrelated to the bs-platform@7 update, see https://github.com/andreas/ocaml-graphql-server/issues/181.

**Comment by leeor** [comment]
Solving the missing variables as part of migrating to bs-platform@7 is required since the newer bs-platform mandates migrating from graphql_ppx to graphql_ppx_re which does not send variables that were not assigned values.

**Comment by sikanhe** [comment]
Great work @leeor

**Pull request merged**
